name: Run tests

on: [push]

jobs:
    test:
        runs-on: ${{matrix.runner}}
        
        strategy:
            matrix:
                runner: [ubuntu-latest, windows-latest]
                file: [circle.py, rectangle.py, square.py, triangle.py]
                python-version: ["3.12.6"]

            fail-fast: false
        
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                python-version: ${{matrix.python-version}}
      
            - name: Run ${{matrix.file}} tests
              run: python -m unittest ${{matrix.file}}
